---
# vars file for host_setup

action: setup # default action: setup. Allowed actions: setup / teardown
skip_grub: false # Flag to skip grub configuration.

# Path to the remote image to download
remote_image: http://download.eng.brq.redhat.com/rhel-8/rel-eng/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/images/rhel-guest-image-8.1-109.x86_64.qcow2
# The remote image can be cached under this name locally to avoid long downloads
image_cache_name: rhel8-base.qcow2
cache_path: /opt/virtio-auto/cache/

local_image_file: /var/lib/libvirt/images/virtio-auto-image.qcow2

cmdline_options: intel_pstate=disable mce=ignore_ce default_hugepagesz=1G hugepagesz=1G hugepages=6 isolcpus=2-7 rcu_nocbs=2-7 nohz_full=2-7 iommu=pt intel_iommu=on

# Testpmd variables
testpmd_session: host-testpmd
nics:
 - "0000:04:00.0"
 - "0000:04:00.1"

# Guest variables
guest_mgt_mac: 52:54:00:f2:2f:4f
guest_mgt_ip: 192.168.200.10
guest_pubkey: guest_id_rsa.pub
guest_name: rhel8-bench
guest_iommu: false  # set to true to configure iommu in the guest

# QEMU specific variables:
# qemu: Variable that controls what to do WRT qemu. Possible values:
#   repo: install it from the repository (i.e: yum install qemu-kvm)
#   local: assume a qemu binary is already installed in 
#       '{{ qemu_install_path }}/usr/local/bin/qemu-system-x86_64'
#        and just use it
#   build: clone qemu, checkout {{ version }}, build it, install it and use it
qemu: repo
# build qemu vars:
qemu_install_path: /opt/virtio-auto/qemu/
qemu_src_path: /opt/virtio-auto/src/qemu/
# version of qemu to build
qemu_version: HEAD

# DPDK specific variables:
# dpdk: Variable that controls what to do WRT dpdk. Possible values:
#   repo: install it from the repository (i.e: yum install dpdk)
#   local: assume a installation in
#       '{{ dpdk_install_path }} and just use it
#   build: clone dpdk, checkout {{ dpdk_version }}, build it, install it and use it
dpdk: repo
# build dpdk vars:
dpdk_install_path: /opt/virtio-auto/dpdk/
dpdk_src_path: /opt/virtio-auto/src/dpdk/
# version of dpdk to build
dpdk_version: HEAD
