
- name: install dependencies
  yum:
   name:
    - dpdk-tools
    - tmux
   state: present

- name: insert vfio module
  modprobe:
    name: vfio
    state: present
    params: enable_unsafe_noiommu_mode=1

- name: insert vfio-pci module
  modprobe:
    name: vfio-pci
    state: present

- name: bind NICS to vfio driver
  command: dpdk-devbind -b vfio-pci {{ item }}
  loop: "{{ nics }}"

- name: killing testpmd if running
  shell: pgrep testpmd | xargs kill
  ignore_errors: true

- name: run testpmd in host
  shell: tmux new-session -s guest-testmpd -d "testpmd -l 0,1,2 --socket-mem 1024 -n 4 --proc-type auto --file-prefix pg -- --portmask=3 --forward-mode=io --port-topology=chained --disable-rss -i --rxq=1 --txq=1 --rxd=256 --txd=256 --nb-cores=2 --auto-start || cat"
  register: guest_testpmd

- debug:
    msg: "cmd: {{ guest_testpmd.cmd }} OUT:{{ guest_testpmd.stdout }} ERR: {{ guest_testpmd.stderr }}"

