---
# tasks file for guest-dpdk
#

- name: install repository
  yum_repository:
    name: virtio-auto-{{ index }}
    description: virtio-auto repository
    baseurl: "{{ item }}"
    gpgcheck: no
  loop: "{{ repos }}"
  loop_control:
    index_var: index

- name: Update grub and reboot
  import_tasks: grub.yml

- name: Run dpdk
  import_tasks: dpdk.yml
