---
# vars file for guest-dpdk
guest_cmdline_options: default_hugepagesz=1G hugepagesz=1G hugepages=1 intel_iommu=on iommu=pt isolcpus=1,2 rcu_nocbs=1,2 nohz_full=1,2

# Set IOMMU support
iommu: false

# repositories to install (or list thereof)
repos:
  -

# nics to use by dpdk
nics:
 - "0000:0a:00.0"
 - "0000:0b:00.0"
