- name: Check if we have hugepages
  shell: awk -e '/Hugepagesize:/ {print $2}' /proc/meminfo
  register: hp_size

- name: Check if needed cmndline options are found
  shell: grep GRUB_CMDLINE_LINUX /etc/default/grub | grep -c "{{ cmdline_options }}"
  register: cmdline_opts
  ignore_errors: true
  when: hp_size.stdout != "1048576"

- name: Edit commandline options
  lineinfile:
    dest: /etc/default/grub
    regexp: 'GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 {{ cmdline_options }}"'
    backrefs: yes
  when:
    - hp_size.stdout != "1048576"
    - cmdline_opts.stdout == "0"

- name: Update bios-based grub
  command: grub2-mkconfig –o /boot/grub2/grub.cfg
  when:
    - hp_size.stdout != "1048576"
    - cmdline_opts.stdout == "0"

- name: reboot if we need it
  reboot:
    test_command: cat /proc/cmdline | grep "{{ cmdline_options }}"
  when:
    - hp_size.stdout != "1048576"
    - cmdline_opts.stdout == "0"

- name: Check if we have managed to configure hugepages
  shell: awk -e '/Hugepagesize:/ {print $2}' /proc/meminfo | grep 1048576
  when: hp_size.stdout != "1048576"
