---
# tasks file for host_setup
#
#
- name: Set cmndline
  import_tasks: grub.yml
  when:
    - action == "setup"
    - skip_grub == false

- name: Prepare server
  import_tasks: prepare.yml
  when: action == "setup"

- name: Setup dpdk
  import_tasks: build-dpdk.yml
  when: action == "setup"

- name: Run dpdk
  import_tasks: testmpd.yml
  when: action == "setup"

- name: Setup QEMU
  import_tasks: build-qemu.yml
  when: action == "setup"

- name: Run VM
  import_tasks: virt.yml
  when: action == "setup"

- name: Tear Down server
  import_tasks: teardown.yml
  when: action == "teardown"
