---
# Tasks to prepare the host

# TODO: It would be nice to selecively not install the main dependencies but
# download the code (specific revision) and build it
- name: install dependencies
  yum:
   name:
    - libvirt
    - qemu-kvm
    - dpdk-tools
   state: present

- name: Check if the image file exists
  stat:
    path: "{{ local_image_file  }}"
  register: local_image

- name: Check that the base image exists
  stat:
    path: "{{ cache_path }}/{{ image_cache_name }}"
  register: base_image
  when: local_image.stat.exists == False

- name: Create cache directory
  file:
    path: "{{ cache_path }}"
    state: directory

- name: download base image
  get_url:
    url: '{{ remote_image }}'
    dest: "{{ cache_path }}/{{ image_cache_name }}"
    mode: '0640'
  when:
    - local_image.stat.exists == False 
    - base_image.stat.exists == False 

- name: copy base image
  copy:
    dest: '{{ local_image_file }}'
    src: "{{ cache_path }}/{{ image_cache_name }}"
    remote_src: true
  when: local_image.stat.exists == False 

- name: upload public ssh key
  copy:
    dest: /tmp/id_rsa.pub
    src: "{{ guest_pubkey }}"
  when: local_image.stat.exists == False 

- name: Install virt-sysprep
  yum:
    name: libguestfs-tools-c
    state: present

- name: prepare_image
  command: >
    virt-sysprep --root-password password:changeme 
                 --uninstall cloud-init 
                 --selinux-relabel 
                 --ssh-inject root:file:/tmp/id_rsa.pub
                 -a {{ local_image_file }}
  when: local_image.stat.exists == False 

