
- name: Stop guest
  virt:
    name: "{{ guest_name }}"
    state: destroyed
    uri: 'qemu:///system'
  ignore_errors: true  # The task fails if vm does not exist

- name: Kill host's dpdk instance
  shell: >
    pgrep testpmd > xargs kill || true
    tmux kill-session -t {{ testmpd_session }}
  ignore_errors: true

- name: Remove guest image
  file:
    path: "{{ local_image_file }}"
    state: absent

- name: Clean used directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
      - "{{ qemu_src_path }}"
      - "{{ qemu_install_path }}"
      - "{{ dpdk_install_path }}"
      - "{{ dpdk_src_path }}"
